"use client";

import { useState, useEffect } from "react";
import { getAddresses, setAddresses } from "@/lib/addresses";
import type { DeployedAddresses } from "@/lib/contracts";

export function AddressConfig({ onUpdate }: { onUpdate: (addr: DeployedAddresses) => void }) {
  const [json, setJson] = useState("");
  const [show, setShow] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const addr = getAddresses();
    if (addr.nofeeswap !== "0x0000000000000000000000000000000000000000") {
      setLoaded(true);
      onUpdate(addr);
    }
  }, [onUpdate]);

  const handleLoad = () => {
    try {
      const parsed = JSON.parse(json);
      setAddresses(parsed);
      onUpdate(parsed);
      setLoaded(true);
      setShow(false);
    } catch (e) {
      alert("Invalid JSON. Paste the contents of deployed-addresses.json");
    }
  };

  const handleLoadFile = async () => {
    try {
      const resp = await fetch("/api/addresses");
      const data = await resp.json();
      setAddresses(data);
      onUpdate(data);
      setLoaded(true);
    } catch {
      alert("Could not load addresses from API. Paste them manually.");
    }
  };

  if (loaded && !show) {
    return (
      <button
        onClick={() => setShow(true)}
        className="text-xs text-gray-500 hover:text-gray-300"
      >
        Contract Addresses Loaded
      </button>
    );
  }

  return (
    <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
      <h3 className="text-sm font-semibold mb-2">Load Contract Addresses</h3>
      <p className="text-xs text-gray-400 mb-3">
        Paste the contents of <code>deployed-addresses.json</code> generated by the deploy script:
      </p>
      <textarea
        value={json}
        onChange={(e) => setJson(e.target.value)}
        className="w-full h-32 bg-gray-800 border border-gray-600 rounded p-2 text-xs font-mono text-gray-300 mb-2"
        placeholder='{"nofeeswap": "0x...", "operator": "0x...", ...}'
      />
      <div className="flex gap-2">
        <button
          onClick={handleLoad}
          className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 rounded text-sm font-medium"
        >
          Load Addresses
        </button>
        {loaded && (
          <button
            onClick={() => setShow(false)}
            className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-sm"
          >
            Cancel
          </button>
        )}
      </div>
    </div>
  );
}
